# Generated by Django 2.2.9 on 2020-01-23 04:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import triduum_resource.cross_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=triduum_resource.cross_app.models.Base.default_meta, editable=False)),
                ('disabled', models.NullBooleanField(default=False, verbose_name='Deactivate')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'Men'), (2, 'Woman')], verbose_name='Gender')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
