# Generated by Django 2.2.7 on 2019-11-23 04:33

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import triduum_resource.cross_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=triduum_resource.cross_app.models.Base.default_meta, editable=False)),
                ('disabled', models.NullBooleanField(default=False, verbose_name='Deactivate')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('students_number', models.PositiveSmallIntegerField(verbose_name='Students number')),
                ('courses_number', models.PositiveSmallIntegerField(verbose_name='Courses number')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=triduum_resource.cross_app.models.Base.default_meta, editable=False)),
                ('disabled', models.NullBooleanField(default=False, verbose_name='Deactivate')),
                ('start_date', models.DateTimeField(null=True, verbose_name='Start date')),
                ('end_date', models.DateTimeField(null=True, verbose_name='Start date')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_settings.Subscription', verbose_name='Subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('disabled', 'name'), name='unique_together_subscriptions'),
        ),
        migrations.AddConstraint(
            model_name='usersubscription',
            constraint=models.UniqueConstraint(fields=('disabled', 'user', 'subscription'), name='unique_together_users_subscriptions'),
        ),
    ]
