# Generated by Django 2.2.7 on 2019-11-23 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_settings', '0003_subscription_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='months_term',
            new_name='days_term',
        ),
    ]
