# Generated by Django 2.2.5 on 2019-11-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_settings', '0004_auto_20191122_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='days_term',
            field=models.PositiveSmallIntegerField(verbose_name='Days term'),
        ),
    ]
