# Generated by Django 2.2.9 on 2020-03-11 01:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import triduum_resource.cross_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        ('platform_settings', '0005_auto_20191124_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StudentSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=triduum_resource.cross_app.models.Base.default_meta, editable=False)),
                ('disabled', models.NullBooleanField(default=False, verbose_name='Deactivate')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Student', verbose_name='Student')),
                ('user_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_settings.UserSubscription', verbose_name='User subscription')),
            ],
            options={
                'verbose_name': 'Student subscription',
                'verbose_name_plural': 'Students subscription',
            },
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='students',
            field=models.ManyToManyField(through='platform_settings.StudentSubscription', to='classroom.Student'),
        ),
    ]
