# Generated by Django 2.2.9 on 2020-03-11 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_settings', '0006_auto_20200310_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubscription',
            name='status',
        ),
    ]
