# Generated by Django 2.2.9 on 2020-03-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_management', '0033_auto_20200217_2306'),
        ('platform_settings', '0007_remove_studentsubscription_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='courses_number',
        ),
        migrations.AddField(
            model_name='subscription',
            name='exercises',
            field=models.ManyToManyField(related_name='exercises_subscription', to='courses_management.Exercise'),
        ),
    ]
