# Generated by Django 2.2.9 on 2020-04-26 17:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import triduum_resource.cross_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_management', '0036_remove_playexerciseresult_result'),
        ('platform_settings', '0009_remove_subscription_exercises'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=triduum_resource.cross_app.models.Base.default_meta, editable=False)),
                ('disabled', models.NullBooleanField(default=False, verbose_name='Deactivate')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_management.Exercise', verbose_name='Student')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_settings.Subscription', verbose_name='Subscription')),
            ],
            options={
                'verbose_name': 'Subscription exercise',
                'verbose_name_plural': 'Subscriptions exercise',
            },
        ),
    ]
