# Generated by Django 2.2.5 on 2019-10-23 01:59

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import triduum_resource.cross_app.fields
import triduum_resource.cross_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=triduum_resource.cross_app.models.Base.default_meta, editable=False)),
                ('disabled', models.NullBooleanField(default=False, verbose_name='Deactivate')),
                ('permission_type', models.PositiveSmallIntegerField(choices=[(1, 'Section'), (2, 'Funcionality')])),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=triduum_resource.cross_app.models.Base.default_meta, editable=False)),
                ('disabled', models.NullBooleanField(default=False, verbose_name='Deactivate')),
                ('company_name', models.CharField(max_length=200, verbose_name='Company name')),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Phone number')),
                ('whatsapp_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Whatsapp number')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Contact email')),
                ('support_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Support email')),
                ('instagram_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Instagram profile name')),
                ('instagram_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Instagram url')),
                ('facebook_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook profile name')),
                ('facebook_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook url')),
            ],
            options={
                'verbose_name': 'Company information',
                'verbose_name_plural': 'Company informations',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=triduum_resource.cross_app.models.Base.default_meta, editable=False)),
                ('disabled', models.NullBooleanField(default=False, verbose_name='Deactivate')),
                ('photo', triduum_resource.cross_app.fields.AutoWebpImageField(blank=True, null=True, upload_to=triduum_resource.cross_app.models.get_user_photo_folder, verbose_name='_(Photo)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=triduum_resource.cross_app.models.Base.default_meta, editable=False)),
                ('disabled', models.NullBooleanField(default=False, verbose_name='Deactivate')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('path', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Path to route')),
                ('hover_text', models.CharField(blank=True, max_length=1300, null=True, verbose_name='Hover text')),
                ('icon_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Icon name')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Order')),
                ('app_permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cross_app.AppPermission')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cross_app.AppSection')),
            ],
        ),
        migrations.AddConstraint(
            model_name='appsection',
            constraint=models.UniqueConstraint(fields=('disabled', 'path'), name='unique_togheter'),
        ),
        migrations.AddConstraint(
            model_name='apppermission',
            constraint=models.UniqueConstraint(fields=('disabled', 'permission', 'permission_type'), name='disabled-permission-permission_type'),
        ),
    ]
