# Generated by Django 2.2.5 on 2019-10-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_app', '0002_appsection_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsection',
            name='admin_required',
            field=models.BooleanField(default=False, verbose_name='Admin required?'),
        ),
    ]
