# Generated by Django 2.2.5 on 2019-10-29 03:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import triduum_resource.cross_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_app', '0004_auto_20191028_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinfo',
            name='disabled',
            field=models.NullBooleanField(default=False, verbose_name='Deactivate'),
        ),
        migrations.AddField(
            model_name='groupinfo',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=triduum_resource.cross_app.models.Base.default_meta, editable=False),
        ),
    ]
