# Generated by Django 2.2.5 on 2019-11-02 01:32

from django.db import migrations
import triduum_resource.cross_app.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cross_app', '0006_auto_20191030_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinformation',
            name='dark_logo',
            field=triduum_resource.cross_app.fields.AutoWebpFileField(blank=True, null=True, upload_to='company_information/logos/', verbose_name='_(Dark logo)'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='light_logo',
            field=triduum_resource.cross_app.fields.AutoWebpFileField(blank=True, null=True, upload_to='company_information/logos/', verbose_name='_(Light logo)'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='short_dark_logo',
            field=triduum_resource.cross_app.fields.AutoWebpFileField(blank=True, null=True, upload_to='company_information/logos/', verbose_name='_(Short light logo)'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='short_light_logo',
            field=triduum_resource.cross_app.fields.AutoWebpFileField(blank=True, null=True, upload_to='company_information/logos/', verbose_name='_(Short light logo)'),
        ),
    ]
