# Generated by Django 2.2.5 on 2019-11-20 02:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import triduum_resource.cross_app.fields
import triduum_resource.cross_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alphabet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=triduum_resource.cross_app.models.Base.default_meta, editable=False)),
                ('disabled', models.NullBooleanField(default=False, verbose_name='Deactivate')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Order')),
                ('letter', models.CharField(max_length=10, verbose_name='Letter')),
                ('pronunciation', models.CharField(max_length=10, verbose_name='Pronunciation')),
                ('image', triduum_resource.cross_app.fields.AutoWebpFileField(blank=True, null=True, upload_to='alphabeth/images/', verbose_name='_(Letter image)')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=triduum_resource.cross_app.models.Base.default_meta, editable=False)),
                ('disabled', models.NullBooleanField(default=False, verbose_name='Deactivate')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Icon name')),
                ('color', models.CharField(blank=True, max_length=20, null=True, verbose_name='Color')),
                ('image', triduum_resource.cross_app.fields.AutoWebpFileField(blank=True, null=True, upload_to='category/images/', verbose_name='_(Category image)')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Order')),
                ('hover_text', models.CharField(blank=True, max_length=1300, null=True, verbose_name='Hover text')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=triduum_resource.cross_app.models.Base.default_meta, editable=False)),
                ('disabled', models.NullBooleanField(default=False, verbose_name='Deactivate')),
                ('name', models.CharField(max_length=30, verbose_name='Language')),
                ('short_name', models.CharField(max_length=6, verbose_name='Short name')),
            ],
        ),
        migrations.AddConstraint(
            model_name='language',
            constraint=models.UniqueConstraint(fields=('disabled', 'name', 'short_name'), name='unique_together_language'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses_management.Category'),
        ),
        migrations.AddField(
            model_name='alphabet',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_management.Language'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('disabled', 'name'), name='unique_together_category'),
        ),
        migrations.AddConstraint(
            model_name='alphabet',
            constraint=models.UniqueConstraint(fields=('disabled', 'language', 'letter'), name='unique_together_alphabet'),
        ),
    ]
