# Generated by Django 2.2.5 on 2019-11-20 03:49

import courses_management.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import triduum_resource.cross_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=triduum_resource.cross_app.models.Base.default_meta, editable=False)),
                ('disabled', models.NullBooleanField(default=False, verbose_name='Deactivate')),
                ('model', models.IntegerField(choices=[(0, 'Alphabet'), (1, 'Category')], default=0)),
                ('related', models.IntegerField(verbose_name='Model related')),
                ('file', models.FileField(upload_to=courses_management.models.directory_path_audio, verbose_name='_(Audio file)')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
