# Generated by Django 2.2.5 on 2019-11-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_management', '0002_audiofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='related',
        ),
        migrations.AddField(
            model_name='audiofile',
            name='related_id',
            field=models.IntegerField(default=0, verbose_name='Related id'),
        ),
    ]
