# Generated by Django 2.2.7 on 2019-11-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_management', '0003_auto_20191119_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon_name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Icon name'),
        ),
    ]
