# Generated by Django 2.2.5 on 2019-11-25 02:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import triduum_resource.cross_app.fields
import triduum_resource.cross_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_management', '0004_auto_20191122_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=triduum_resource.cross_app.models.Base.default_meta, editable=False)),
                ('disabled', models.NullBooleanField(default=False, verbose_name='Deactivate')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='Icon name')),
                ('image', triduum_resource.cross_app.fields.AutoWebpFileField(blank=True, null=True, upload_to='object/images/', verbose_name='_(Category image)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_management.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
