# Generated by Django 2.2.7 on 2019-12-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_management', '0006_auto_20191124_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='audio_divition',
            field=models.IntegerField(choices=[(1, 'The whole word'), (2, 'Letter'), (3, 'Segment')], default=1, verbose_name='Audio Divition'),
        ),
    ]
