# Generated by Django 2.2.7 on 2019-12-01 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_management', '0007_audiofile_audio_divition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiofile',
            old_name='audio_divition',
            new_name='divition',
        ),
    ]
