# Generated by Django 2.2.7 on 2019-12-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_management', '0008_auto_20191201_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='divition',
        ),
        migrations.AddField(
            model_name='audiofile',
            name='division',
            field=models.IntegerField(choices=[(1, 'The whole word'), (2, 'Letter'), (3, 'Segment')], default=1, verbose_name='Audio Division'),
        ),
    ]
