# Generated by Django 2.2.7 on 2019-12-10 04:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import triduum_resource.cross_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_management', '0010_audiofile_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=triduum_resource.cross_app.models.Base.default_meta, editable=False)),
                ('disabled', models.NullBooleanField(default=False, verbose_name='Deactivate')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('video_url', models.CharField(max_length=250, verbose_name='Url')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=triduum_resource.cross_app.models.Base.default_meta, editable=False)),
                ('disabled', models.NullBooleanField(default=False, verbose_name='Deactivate')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('video_url', models.CharField(max_length=250, verbose_name='Url')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=triduum_resource.cross_app.models.Base.default_meta, editable=False)),
                ('disabled', models.NullBooleanField(default=False, verbose_name='Deactivate')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_management.Section')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=triduum_resource.cross_app.models.Base.default_meta, editable=False)),
                ('disabled', models.NullBooleanField(default=False, verbose_name='Deactivate')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_management.Exercise')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_management.Object')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_management.Level'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='objects',
            field=models.ManyToManyField(blank=True, through='courses_management.ExerciseObject', to='courses_management.Object'),
        ),
    ]
