# Generated by Django 2.2.7 on 2019-12-10 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_management', '0011_auto_20191209_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='objects',
        ),
    ]
