# Generated by Django 2.2.7 on 2019-12-17 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_management', '0013_auto_20191211_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alphabet',
            name='language',
        ),
    ]
