# Generated by Django 2.2.7 on 2019-12-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_management', '0014_remove_alphabet_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='level',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Order'),
        ),
    ]
