# Generated by Django 2.2.7 on 2019-12-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_management', '0015_auto_20191218_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='name',
            field=models.CharField(default='', max_length=250, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
