# Generated by Django 2.2.7 on 2019-12-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_management', '0016_exercise_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Order'),
        ),
    ]
