# Generated by Django 2.2.7 on 2019-12-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_management', '0017_audiofile_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='video_url',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='section',
            name='video_url',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Url'),
        ),
    ]
