# Generated by Django 2.2.7 on 2019-12-31 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_management', '0018_auto_20191226_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Color'),
        ),
    ]
