# Generated by Django 2.2.7 on 2020-01-06 15:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import triduum_resource.cross_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_management', '0019_exercise_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=triduum_resource.cross_app.models.Base.default_meta, editable=False)),
                ('disabled', models.NullBooleanField(default=False, verbose_name='Deactivate')),
                ('results', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_management.Exercise')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayExerciseStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=triduum_resource.cross_app.models.Base.default_meta, editable=False)),
                ('disabled', models.NullBooleanField(default=False, verbose_name='Deactivate')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Playing'), (2, 'Terminated')], verbose_name='Status')),
                ('exercise_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_management.PlayExercise')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
