# Generated by Django 2.2.7 on 2020-01-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_management', '0020_playexercise_playexercisestatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playexercisestatus',
            old_name='exercise_run',
            new_name='exercise_play',
        ),
    ]
