# Generated by Django 2.2.7 on 2020-01-06 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_management', '0021_auto_20200106_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playexercisestatus',
            old_name='exercise_play',
            new_name='play_exercise',
        ),
    ]
