# Generated by Django 2.2.7 on 2020-01-08 04:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_management', '0023_auto_20200106_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='definition',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Definition'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.PositiveIntegerField(choices=[(1, 'Pronunciation'), (2, 'Rhyming images')], default=1, verbose_name='Exercise type'),
        ),
    ]
