# Generated by Django 2.2.9 on 2020-01-23 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_management', '0025_auto_20200121_2054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
