# Generated by Django 2.2.7 on 2020-01-29 04:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import triduum_resource.cross_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_management', '0028_playexercise_results'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playexercise',
            name='results',
        ),
        migrations.RemoveField(
            model_name='playexercisestatus',
            name='play_exercise',
        ),
        migrations.CreateModel(
            name='PlayExerciseTry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=triduum_resource.cross_app.models.Base.default_meta, editable=False)),
                ('disabled', models.NullBooleanField(default=False, verbose_name='Deactivate')),
                ('try_number', models.PositiveSmallIntegerField(verbose_name='Try number')),
                ('play_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_management.PlayExercise')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayExerciseResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=triduum_resource.cross_app.models.Base.default_meta, editable=False)),
                ('disabled', models.NullBooleanField(default=False, verbose_name='Deactivate')),
                ('result', models.PositiveSmallIntegerField(choices=[(1, 'Success'), (2, 'Fail')], verbose_name='Result')),
                ('running_definition', django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Running definition')),
                ('play_exercise_retry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_management.PlayExerciseTry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='playexercisestatus',
            name='play_exercise_retry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses_management.PlayExerciseTry'),
        ),
    ]
