# Generated by Django 2.2.7 on 2020-01-29 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_management', '0029_auto_20200128_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playexerciseresult',
            old_name='play_exercise_retry',
            new_name='play_exercise_try',
        ),
        migrations.RenameField(
            model_name='playexercisestatus',
            old_name='play_exercise_retry',
            new_name='play_exercise_try',
        ),
    ]
