# Generated by Django 2.2.5 on 2020-02-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_management', '0030_auto_20200129_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.PositiveIntegerField(choices=[(1, 'Pronunciation'), (2, 'Rhyming images'), (3, 'Correct image')], default=1, verbose_name='Exercise type'),
        ),
    ]
