# Generated by Django 2.2.9 on 2020-02-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_management', '0031_auto_20200210_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.PositiveIntegerField(choices=[(1, 'Pronunciation'), (2, 'Rhyming images'), (3, 'Correct image'), (4, 'Rhyming images (2 - 2)')], default=1, verbose_name='Exercise type'),
        ),
    ]
