# Generated by Django 2.2.9 on 2020-02-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_management', '0032_auto_20200217_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.PositiveIntegerField(choices=[(1, 'Pronunciation'), (2, 'Rhyming images'), (3, 'Correct image'), (4, 'Rhyming images (2 - 2)'), (5, 'Alphabet sounds')], default=1, verbose_name='Exercise type'),
        ),
    ]
