# Generated by Django 2.2.9 on 2020-04-18 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20200415_1909'),
        ('courses_management', '0033_auto_20200217_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='playexercise',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classroom.Student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playexerciseresult',
            name='qualification',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Showed'), (2, 'Practiced'), (3, 'Master')], default=1, verbose_name='Qualification'),
            preserve_default=False,
        ),
    ]
