# Generated by Django 2.2.9 on 2020-04-28 01:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import triduum_resource.cross_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20200415_1909'),
        ('courses_management', '0036_remove_playexerciseresult_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationTeacherExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=triduum_resource.cross_app.models.Base.default_meta, editable=False)),
                ('disabled', models.NullBooleanField(default=False, verbose_name='Deactivate')),
                ('qualification', models.PositiveSmallIntegerField(choices=[(1, 'Showed'), (2, 'Practiced'), (3, 'Master')], verbose_name='Qualification exercise')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_management.Exercise')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
