# Generated by Django 2.2.9 on 2020-04-28 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_management', '0037_qualificationteacherexercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualificationteacherexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='courses_management.Exercise'),
        ),
    ]
