# Generated by Django 2.2.9 on 2020-05-01 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_management', '0038_auto_20200427_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playexercisestatus',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Created'), (2, 'Playing'), (3, 'Terminated'), (4, 'Exited')], verbose_name='Status'),
        ),
    ]
